api_platform:
    title: Hello Robot Dance-Offs API
    version: 3.2
    
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    mapping:
        paths: 
            - '%kernel.project_dir%/src/'