api_platform:
    title: Hello Robot Dance-Offs API
    version: 3.2
    formats:
        
        json: [ 'application/json' ]
     
    
    docs_formats:
        jsonld: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    mapping:
        paths: 
            - '%kernel.project_dir%/src/'
    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']